GET http://localhost:3000/api/cars
###

GET http://localhost:3000/api/cars/2
Content-Type: application/json
###

POST http://localhost:3000/api/cars
Content-Type: application/json

{
 "brand": "Mercedes", 
 "model": "S500",
 "year": "2003"
  }
###

DELETE http://localhost:3000/api/cars/f8fa


###

PUT http://localhost:3000/api/cars/2f02
Content-Type: application/json

{
 "model": "V70"
 }
